import os
from graph.state import AgentState
from mcp.tool_loader import loader
from config import config

class VoiceSynth:
    def run(self, task: dict) -> dict:
        """
        Processes a single scene task generated by the scene parser.
        Executed in parallel per scene.
        """
        scene_id = task.get("scene_id")
        audio_tasks = task.get("audio_tasks", [])
        
        output_data = {"scene_id": scene_id, "audio_files": []}
        
        for i, dlg in enumerate(audio_tasks):
            char = dlg.get("character", "Narrator")
            line = dlg.get("line", "")
            
            out_file = os.path.join(config.raw_scenes_dir, f"scene_{scene_id}_audio_{i}_{char}.wav")
            # Synthesize voice
            result_path = loader.invoke(
                "voice_cloning_synthesizer",
                character=char,
                text=line,
                output_path=out_file
            )
            output_data["audio_files"].append(result_path)
            
        print(f"[VoiceSynth] Generated {len(audio_tasks)} audio clips for Scene {scene_id}.")
        return {"audio_tracks": [output_data]}
